# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e874fedcd7b56170e172ce95259ef657c7846209c461d088c5ac235b93935cc42a42e0d410d7242f273b980c32b404d252a4e9184fc06ff4214466dd154b250

test:
  secret_key_base: fd1f5d08a05049cbfecb6d2c2b34d7f09851b6ae764b8e6737ee473823fc6be1bd16eb9f4f0cc4acb53046af8c0c7a8d8695324dd2a9d79d6908c24eb2bc48f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
